const ALLOWED_STATES=new Set(["NC","SC","GA","IL","FL"]);
function json(body,status=200){return new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}})}
function clean(v,max=250){return typeof v==="string"?v.trim().replace(/\s+/g," ").slice(0,max):""}
function phone(v){const d=String(v||"").replace(/\D/g,"");return d.length===11&&d.startsWith("1")?d.slice(1):d}
function email(v){return String(v||"").trim().toLowerCase()}
function validEmail(v){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)}
function validPhone(v){return /^\d{10}$/.test(v)}
function allowedOrigin(request,env){const o=request.headers.get("Origin");if(!o)return true;const extra=clean(env.ALLOWED_ORIGINS||"",1000).split(",").map(x=>x.trim()).filter(Boolean);return ["https://jaharasad.com","https://www.jaharasad.com",...extra].includes(o)}
function trackingFromUrl(v){try{const u=new URL(v);return{utm_source:u.searchParams.get("utm_source")||"",utm_medium:u.searchParams.get("utm_medium")||"",utm_campaign:u.searchParams.get("utm_campaign")||"",qr_id:u.searchParams.get("qr_id")||"",fbclid:u.searchParams.get("fbclid")||""}}catch{return{utm_source:"",utm_medium:"",utm_campaign:"",qr_id:"",fbclid:""}}}
async function supabase(env,path,init={}){const h=new Headers(init.headers||{});h.set("apikey",env.SUPABASE_SERVICE_ROLE_KEY);h.set("Authorization",`Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`);h.set("Content-Type","application/json");h.set("Accept","application/json");const r=await fetch(`${env.SUPABASE_URL.replace(/\/$/,"")}/rest/v1/${path}`,{...init,headers:h});if(!r.ok)throw new Error(`Supabase ${r.status}: ${(await r.text()).slice(0,400)}`);const t=await r.text();return t?JSON.parse(t):null}
async function existing(env,e,p){if(e){const r=await supabase(env,`families?select=id&email=eq.${encodeURIComponent(e)}&limit=1`);if(Array.isArray(r)&&r[0])return r[0]}if(p){const r=await supabase(env,`families?select=id&phone=eq.${encodeURIComponent(p)}&limit=1`);if(Array.isArray(r)&&r[0])return r[0]}return null}
export async function onRequestPost({request,env}){
 if(!env.SUPABASE_URL||!env.SUPABASE_SERVICE_ROLE_KEY)return json({ok:false,error:"Lead intake is not configured."},503);
 if(!allowedOrigin(request,env))return json({ok:false,error:"Origin not allowed."},403);
 let b;try{b=await request.json()}catch{return json({ok:false,error:"Invalid request body."},400)}
 if(clean(b.company,100))return json({ok:true});
 const started=Number(b.form_started_at||0);if(started&&Date.now()-started<1800)return json({ok:false,error:"Please wait a moment and try again."},429);
 const first=clean(b.first_name,80),last=clean(b.last_name,80),e=email(b.email),p=phone(b.phone),state=clean(b.state,2).toUpperCase(),timeframe=clean(b.timeframe,80),preferred=clean(b.preferred_contact,30),consent=b.consent===true||b.consent==="true"||b.consent==="on";
 const errors={};if(!first)errors.first_name="First name is required.";if(!last)errors.last_name="Last name is required.";if(!validEmail(e))errors.email="Enter a valid email address.";if(!validPhone(p))errors.phone="Enter a 10-digit mobile number.";if(!ALLOWED_STATES.has(state))errors.state="Choose a service state.";if(!timeframe)errors.timeframe="Choose a timeframe.";if(!preferred)errors.preferred_contact="Choose a contact method.";if(!consent)errors.consent="Consent is required.";if(Object.keys(errors).length)return json({ok:false,error:"Please correct the highlighted fields.",fields:errors},422);
 const pageUrl=clean(b.page_url||request.headers.get("Referer")||"",500),fromUrl=trackingFromUrl(pageUrl),utmSource=clean(b.utm_source||fromUrl.utm_source,100),utmMedium=clean(b.utm_medium||fromUrl.utm_medium,100),utmCampaign=clean(b.utm_campaign||fromUrl.utm_campaign,150),qrId=clean(b.qr_id||fromUrl.qr_id,100),fbclid=clean(b.fbclid||fromUrl.fbclid,250);
 const details=["Campaign: DSCR Investors",`Property state: ${state}`,`Timing: ${timeframe}`,`Preferred contact: ${preferred}`,clean(b.property_type,80)?`Property type: ${clean(b.property_type,80)}`:"",clean(b.purchase_price,50)?`Purchase price: ${clean(b.purchase_price,50)}`:"",clean(b.monthly_rent,50)?`Estimated monthly rent: ${clean(b.monthly_rent,50)}`:"",clean(b.monthly_taxes,50)?`Estimated monthly taxes: ${clean(b.monthly_taxes,50)}`:"",clean(b.monthly_insurance,50)?`Estimated monthly insurance: ${clean(b.monthly_insurance,50)}`:"",clean(b.monthly_hoa,50)?`Estimated monthly HOA: ${clean(b.monthly_hoa,50)}`:"",clean(b.down_payment,50)?`Down payment: ${clean(b.down_payment,50)}`:"",clean(b.primary_question,300)?`Goal/question: ${clean(b.primary_question,300)}`:"",utmSource?`UTM source: ${utmSource}`:"",utmMedium?`UTM medium: ${utmMedium}`:"",utmCampaign?`UTM campaign: ${utmCampaign}`:"",qrId?`QR ID: ${qrId}`:"",fbclid?`Facebook click ID: ${fbclid}`:"",pageUrl?`Landing page: ${pageUrl}`:""].filter(Boolean).join("\n");
 const payload={first_name:first,last_name:last,household_name:`${first} ${last}`.trim(),email:e,phone:p,state,contact_type:"investor",relationship_status:"new",email_marketing_consent:consent,direct_mail_eligible:false,do_not_mail:false,source:"Website | DSCR Investors",notes:details};
 try{const ex=await existing(env,e,p);let familyId,disposition;if(ex?.id){familyId=ex.id;disposition="updated";await supabase(env,`families?id=eq.${encodeURIComponent(familyId)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify(payload)})}else{disposition="created";const rows=await supabase(env,"families?select=id",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify(payload)});familyId=Array.isArray(rows)?rows[0]?.id:rows?.id;if(!familyId)throw new Error("No family ID returned")}
 await supabase(env,"contact_timeline",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({family_id:familyId,event_type:"website_lead",title:"New DSCR Investor lead",details:`Lead ${disposition} from DSCR landing page.\n${details}`})});return json({ok:true,message:"Thank you. Your DSCR property analysis request was received.",disposition})}catch(err){console.error("DSCR lead intake error:",err);return json({ok:false,error:"We could not save your information right now. Please call 919-200-3359."},500)}
}
export async function onRequestOptions({request,env}){if(!allowedOrigin(request,env))return new Response(null,{status:403});return new Response(null,{status:204,headers:{"Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type","Access-Control-Max-Age":"86400"}})}