const ALLOWED_CAMPAIGNS = {
  "first-time-homebuyer": { label:"First-Time Homebuyer", source:"Website | First-Time Homebuyer" },
  "down-payment-assistance": { label:"Down Payment Assistance", source:"Website | Down Payment Assistance" },
  "reverse-mortgage": { label:"Reverse Mortgage / HECM", source:"Website | Reverse Mortgage" },
  "buyer-plan": { label:"Buyer Plan", source:"Website | Buyer Plan" },
  "search-homes": { label:"Search Homes", source:"Website | Search Homes" },
  "preapproval": { label:"Mortgage Pre-Approval", source:"Website | Mortgage Pre-Approval" },
  "fha": { label:"FHA Financing", source:"Website | FHA" },
  "va": { label:"VA Financing", source:"Website | VA" },
  "usda": { label:"USDA Financing", source:"Website | USDA" },
  "conventional": { label:"Conventional Financing", source:"Website | Conventional" },
  "refinance": { label:"Refinance", source:"Website | Refinance" },
  "condo-financing": { label:"Condo Financing", source:"Website | Condo Financing" },
  "manufactured-homes": { label:"Manufactured Home Financing", source:"Website | Manufactured Homes" },
  "investment-properties": { label:"Investment Property / DSCR Financing", source:"Website | Investment Properties" },
  "new-construction": { label:"New Construction", source:"Website | New Construction" },
  "seller-strategy": { label:"Seller Strategy", source:"Website | Seller Strategy" },
  "home-value": { label:"Home Value Review", source:"Website | Home Value" },
  "strategic-pricing": { label:"Strategic Pricing Review", source:"Website | Strategic Pricing" },
  "seller-roadmap": { label:"Seller Roadmap", source:"Website | Seller Roadmap" },
  "net-proceeds": { label:"Seller Net Proceeds", source:"Website | Net Proceeds" },
  "sell-and-buy": { label:"Sell and Buy Strategy", source:"Website | Sell and Buy" },
  "pre-foreclosure": { label:"Pre-Foreclosure Help", source:"Website | Pre-Foreclosure" },
  "homeowner-solutions": { label:"Homeowner Solutions", source:"Website | Homeowner Solutions" },
  "inherited-property": { label:"Inherited Property", source:"Website | Inherited Property" },
  "housing-transition": { label:"Housing Transition", source:"Website | Housing Transition" },
  "realtor-partner": { label:"Realtor Partnership", source:"Website | Realtor Partner" },
  "lending-partner": { label:"Lending Partnership", source:"Website | Lending Partner" },
  "professional-partner": { label:"Professional Partnership", source:"Website | Professional Partner" },
  "submit-referral": { label:"Professional Referral", source:"Website | Referral" },
  "rent-vs-own": { label:"Rent vs. Own", source:"Website | Rent vs. Own" },
  "general": { label:"General Consultation", source:"Website | General Consultation" }
};
const CAMPAIGN_ALIASES={"New Construction":"new-construction","reverse-mortgage-hecm":"reverse-mortgage","pre-foreclosure-solutions":"pre-foreclosure","usda-0-down":"usda"};
const ALLOWED_STATES=new Set(["NC","SC","GA","IL","FL"]);
function json(body,status=200,extra={}){return new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store",...extra}})}
function cleanText(value,max=250){if(typeof value!=="string")return"";return value.trim().replace(/\s+/g," ").slice(0,max)}
function normalizePhone(value){const digits=String(value||"").replace(/\D/g,"");return digits.length===11&&digits.startsWith("1")?digits.slice(1):digits}
function normalizeEmail(value){return String(value||"").trim().toLowerCase()}
function validEmail(value){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)}
function validPhone(value){return /^\d{10}$/.test(value)}
function splitName(value){const parts=cleanText(value,160).split(" ").filter(Boolean);return {first:parts.shift()||"",last:parts.join(" ")||"Not provided"}}
function allowedOrigin(request,env){const origin=request.headers.get("Origin");if(!origin)return true;const configured=cleanText(env.ALLOWED_ORIGINS||"",1000).split(",").map(x=>x.trim()).filter(Boolean);return["https://jaharasad.com","https://www.jaharasad.com",...configured].includes(origin)}
async function readBody(request){const type=(request.headers.get("content-type")||"").toLowerCase();if(type.includes("application/json"))return await request.json();if(type.includes("application/x-www-form-urlencoded")||type.includes("multipart/form-data")){const fd=await request.formData();return Object.fromEntries(fd.entries())}try{return await request.json()}catch{const fd=await request.formData();return Object.fromEntries(fd.entries())}}
function trackingFromUrl(value){try{const u=new URL(value);return {utm_source:u.searchParams.get("utm_source")||"",utm_medium:u.searchParams.get("utm_medium")||"",utm_campaign:u.searchParams.get("utm_campaign")||"",qr_id:u.searchParams.get("qr_id")||"",fbclid:u.searchParams.get("fbclid")||""}}catch{return {utm_source:"",utm_medium:"",utm_campaign:"",qr_id:"",fbclid:""}}}
async function supabaseFetch(env,path,init={}){const url=`${env.SUPABASE_URL.replace(/\/$/,"")}/rest/v1/${path}`;const headers=new Headers(init.headers||{});headers.set("apikey",env.SUPABASE_SERVICE_ROLE_KEY);headers.set("Authorization",`Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`);headers.set("Content-Type","application/json");headers.set("Accept","application/json");const response=await fetch(url,{...init,headers});if(!response.ok){const text=await response.text();throw new Error(`Supabase ${response.status}: ${text.slice(0,500)}`)}const text=await response.text();return text?JSON.parse(text):null}
async function findExistingFamily(env,email,phone){if(email){const rows=await supabaseFetch(env,`families?select=id,email,phone&email=eq.${encodeURIComponent(email)}&limit=1`);if(Array.isArray(rows)&&rows[0])return rows[0]}if(phone){const rows=await supabaseFetch(env,`families?select=id,email,phone&phone=eq.${encodeURIComponent(phone)}&limit=1`);if(Array.isArray(rows)&&rows[0])return rows[0]}return null}
function diagnostic(error,stage){const raw=String(error?.message||error||"");const match=raw.match(/Supabase\s+(\d{3})\s*:\s*([\s\S]*)/);let status=null,detail="";if(match){status=Number(match[1]);try{const parsed=JSON.parse(match[2]);detail=[parsed?.code,parsed?.message,parsed?.details,parsed?.hint].filter(Boolean).join(" | ")}catch{detail=match[2]}}else{detail=raw}return {stage,status,detail:cleanText(detail,280)}}
export async function onRequestPost(context){const{request,env}=context;if(!env.SUPABASE_URL||!env.SUPABASE_SERVICE_ROLE_KEY)return json({ok:false,error:"Lead intake is not configured."},503);if(!allowedOrigin(request,env))return json({ok:false,error:"Origin not allowed."},403);let body;try{body=await readBody(request)}catch{return json({ok:false,error:"Invalid request body."},400)}if(cleanText(body.company,100))return json({ok:true},200);const startedAt=Number(body.form_started_at||0);if(startedAt&&Date.now()-startedAt<1800)return json({ok:false,error:"Please wait a moment and try again."},429);const rawCampaign=cleanText(body.campaign,60),campaignKey=CAMPAIGN_ALIASES[rawCampaign]||rawCampaign,campaign=ALLOWED_CAMPAIGNS[campaignKey];if(!campaign)return json({ok:false,error:"Invalid campaign."},400);const fallbackName=splitName(body.name||"");const firstName=cleanText(body.first_name,80)||fallbackName.first,lastName=cleanText(body.last_name,80)||fallbackName.last,email=normalizeEmail(body.email),phone=normalizePhone(body.phone),state=cleanText(body.state,2).toUpperCase(),timeframe=cleanText(body.timeframe||body.timeline,80)||"Not provided",housingStatus=cleanText(body.housing_status||body.home_status||body.payment_status||body.property_type||body.stage,80)||"Not provided",preferredContact=cleanText(body.preferred_contact,30)||"Phone/Text",obstacle=cleanText(body.primary_obstacle||body.primary_question||body.message||body.goal,160),pageUrl=cleanText(body.page_url||request.headers.get("Referer")||"",500),fromUrl=trackingFromUrl(pageUrl),fbclid=cleanText(body.fbclid||fromUrl.fbclid,250),utmSource=cleanText(body.utm_source||fromUrl.utm_source,100),utmMedium=cleanText(body.utm_medium||fromUrl.utm_medium,100),utmCampaign=cleanText(body.utm_campaign||fromUrl.utm_campaign,150),qrId=cleanText(body.qr_id||fromUrl.qr_id,100),consent=body.consent===true||body.consent==="true"||body.consent==="on";const errors={};if(!firstName)errors.first_name="First name is required.";if(!lastName)errors.last_name="Last name is required.";if(email&&!validEmail(email))errors.email="Enter a valid email address.";if(!validPhone(phone))errors.phone="Enter a 10-digit mobile number.";if(state&&!ALLOWED_STATES.has(state))errors.state="Choose a licensed service state.";if(!consent)errors.consent="Consent is required before submitting.";if(Object.keys(errors).length)return json({ok:false,error:"Please correct the highlighted fields.",fields:errors},422);
const notes=[`Campaign: ${campaign.label}`,`Timeframe: ${timeframe}`,`Housing status: ${housingStatus}`,`Preferred contact: ${preferredContact}`,obstacle?`Primary goal / question: ${obstacle}`:"",utmSource?`UTM source: ${utmSource}`:"",utmMedium?`UTM medium: ${utmMedium}`:"",utmCampaign?`UTM campaign: ${utmCampaign}`:"",qrId?`QR ID: ${qrId}`:"",fbclid?`Facebook click ID: ${fbclid}`:"",pageUrl?`Landing page: ${pageUrl}`:""].filter(Boolean).join("\n");
let stage="find_family";try{const existing=await findExistingFamily(env,email,phone);let familyId,disposition;if(existing?.id){familyId=existing.id;disposition="updated";stage="update_family";const updatePayload={first_name:firstName,last_name:lastName,household_name:`${firstName} ${lastName}`.trim(),email,phone,state,email_marketing_consent:consent};await supabaseFetch(env,`families?id=eq.${encodeURIComponent(familyId)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify(updatePayload)})}else{disposition="created";stage="create_family";const createPayload={first_name:firstName,last_name:lastName,household_name:`${firstName} ${lastName}`.trim(),email,phone,state,relationship_status:"new",email_marketing_consent:consent,direct_mail_eligible:false,do_not_mail:false,source:campaign.source,notes};const rows=await supabaseFetch(env,"families?select=id",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify(createPayload)});familyId=Array.isArray(rows)?rows[0]?.id:rows?.id;if(!familyId)throw new Error("CRM record created but no family ID was returned.")}stage="create_timeline";let timelineSaved=true,timelineDiagnostic=null;try{await supabaseFetch(env,"contact_timeline",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({family_id:familyId,event_type:"website_lead",title:`New ${campaign.label} lead`,details:`Lead ${disposition} from website.\n${notes}`})})}catch(timelineError){timelineSaved=false;timelineDiagnostic=diagnostic(timelineError,"create_timeline");console.error("Lead timeline error:",timelineDiagnostic)}return json({ok:true,message:"Thank you. Your information was received.",disposition,timeline_saved:timelineSaved,...(!timelineSaved?{warning:"Lead saved; timeline entry could not be recorded.",diagnostic:timelineDiagnostic}:{})})}catch(error){const d=diagnostic(error,stage);console.error("Lead intake error:",d);return json({ok:false,error:"We could not save your information right now. Please call 919-200-3359.",diagnostic:d},500)}}
export async function onRequestOptions(context){if(!allowedOrigin(context.request,context.env))return new Response(null,{status:403});return new Response(null,{status:204,headers:{"Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type","Access-Control-Max-Age":"86400"}})}